### ISSUE TITLE
Black Screen on Control, number 209

### ISSUE THREAD

**Issue by DBoger82** [jojos38/ancubic-kobra-dark-ui#10]
When hitting the control button a black screen with the number 209 appears in the upper left hand corner. None of the control features show up, but if you know where to push on the screen the buttons are there. This is on V1.1 English.

**Comment by SineVVAVz** [comment]
I've seen the same thing. Rarely happens. Reset power and it's gone. Hasn't affected printing for me though.

**Comment by jojos38** [comment]
Mh that's interesting, fixing it would be a pain though with all the languages to update, I'll see when I get some time for now I'm quite busy

**Comment by wabbitguy** [comment]
I have the 209 issue as well, just installed the UI. Looks 1000 times better than the stock one did thats for sure. Just need the 209 to go away and the controls show up. Also using the 1.1V English.

**Comment by jojos38** [comment]
Apologies for the long delay for fixing, I will try to do that this evening if I can

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/10450019/DWIN_SET.zip)
Hey, can you try this version and tell me if it fixed the bug please?

**Comment by wabbitguy** [comment]
@jojos38 Works perfect for the settings both from the main page and while in the Print mode.

In the Print mode there is a "back" button at the bottom of the display that shows but is none functional. The "back" at the top right corner of the display works exactly the same as always though so one can return to the Print screen.

**Comment by jojos38** [comment]
> @jojos38 Works perfect for the settings both from the main page and while in the Print mode.
> 
> In the Print mode there is a "back" button at the bottom of the display that shows but is none functional. The "back" at the top right corner of the display works exactly the same as always though so one can return to the Print screen.

[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/10451074/DWIN_SET.zip)

Can you try this one as a fix for the back button please?
If it doesn't work I have another solution too

**Comment by wabbitguy** [comment]
@jojos38 put in the new DWIN set, the .icl file shows 000, not 001 as prior versions did.

While the settings look good when accessed from the main screen, if you access them using the settings button on the print screen, they show like this:

![Settings](https://user-images.githubusercontent.com/8953419/213323162-61313d74-8deb-4580-be72-a9c3055db4f0.jpg)

The "back button" at the bottom it turns the light on/off, but you tap the LIGHTBULB icon at the top left it goes BACK. LOL

**Comment by wabbitguy** [comment]
@jojos38 the last zip file I tried was missing the 16_68_.icl file in the zip.

BTW, thanks for taking the time to work on this. Much appreciated.

Mel

**Comment by jojos38** [comment]
> @jojos38 put in the new DWIN set, the .icl file shows 000, not 001 as prior versions did.
> 
> While the settings look good when accessed from the main screen, if you access them using the settings button on the print screen, they show like this:
> 
> ![Settings](https://user-images.githubusercontent.com/8953419/213323162-61313d74-8deb-4580-be72-a9c3055db4f0.jpg)
> 
> The "back button" at the bottom it turns the light on/off, but you tap the LIGHTBULB icon at the top left it goes BACK. LOL

OH, I inverted both buttons haha, I will fix that this evening. I did not provide the .icl file because there were no changes on it for the my small fix. I will put the .icl file in the zip when doing the release
Thanks for your time testing my fixes btw, I don't have the screen anymore on my Kobra I can't test it

**Comment by jojos38** [comment]
[DWIN_SET.zip](https://github.com/jojos38/anycubic-kobra-dark-ui/files/10459671/DWIN_SET.zip)
This one should be working fine

**Comment by wabbitguy** [comment]
@jojos38 Just tested. Installed as you outlined in the original repository readme. 

Works perfect. You can close all the issues.

Lightbulb turns print light on and off. Both back buttons work. All options can be changed. Well done!

Since you don't use the screen any more, is there any chance I could fork your work and obtain the hwi file as well? I have my own GitHub site for the Kobra Max firmware that I forked from Anycubic. It'd be nice to have the display setup as well. Providing I could figure out the DGUS editing software...LOL

Second, I'm curious as to what display you are using on your Kobra. I've found the majority of the touch screens have such limited functionality compared to what Marlin can do it's depressing. They don't handle GCODES like M600, M0, M117, M73 and the list goes on. I've repurposed one of the buttons to allow a "continue" instead of a "pause" for the touch screen so I can do filament changes with M600.

Thanks again for the prompt attention and fixes. They make the screen look far better than that 1950's B&W TV appearance!

Mel
btw.. if the Kobra uses a TriGorilla Pro A V1.0.4. there's a bug on the PCB. You can't switch stealthchop and spreadcycle independently on X and E0, if you wanted to use linear advance. They put a resistor in the wrong place so the UART control is screwed up.

**Comment by jojos38** [comment]
Thank you for testing! I'll release it asap

> is there any chance I could fork your work and obtain the hwi file as well

I'm not sure what you mean but if you mean taking mine as a base to make one for the Kobra Max yeah you can as long as you credit me

> I'm curious as to what display you are using on your Kobra

I'm not using any display since I have Octoprint, I'm too lazy to install another one

> You can't switch stealthchop and spreadcycle independently on X and E0

Yeah I'm aware of that, that's rather unfortunate that's why I said it's probably unfixable. I burnt my mother by trying to fix that haha, hence why I went with an SKR 3 EZ

**Comment by wabbitguy** [comment]
> Thank you for testing! I'll release it asap
> 
@jojos38 I'll wait for the release/update then I'll fork it to my Github page and of course give you credit.

> I'm not using any display since I have Octoprint, I'm too lazy to install another one
>
Octoprint, got it. Tried that but it doesn't run deltas at all so I bought Repetier Server Pro to run 3 deltas and 3 cartesians from a single Raspberry PI via a USB hub at the same time.

Thanks for all the hard work!

**Comment by jojos38** [comment]
> > Thank you for testing! I'll release it asap
> 
> @jojos38 I'll wait for the release/update then I'll fork it to my Github page and of course give you credit.
> 
> > I'm not using any display since I have Octoprint, I'm too lazy to install another one
> 
> Octoprint, got it. Tried that but it doesn't run deltas at all so I bought Repetier Server Pro to run 3 deltas and 3 cartesians from a single Raspberry PI via a USB hub at the same time.
> 
> Thanks for all the hard work!

No problem, have fun with your printer!
